### ISSUE TITLE
installation/training fails unless run from scripts folder

### ISSUE THREAD

**Issue by stanleyjs** [pnpnpn/dna2vec#4]
```
$ python3 ./scripts/train_dna2vec.py -c configs/small_example.yml
Traceback (most recent call last):
  File "./scripts/train_dna2vec.py", line 12, in <module>
    from attic_util.time_benchmark import Benchmark
ImportError: No module named 'attic_util'

```
this is executed from `~/dna2vec`

The reason for this is in` train_dna2vec.py `the relative path to `attic_util` and `dna2vec` are appended to `sys.path`.  Idiosyncratically, python appends the '../' from the folder that the script was called from.

the work around is easy - just call the script from within `./scripts`

for cleaner implementation though, it might be better to consider using an egg or some other setup that allows attic_utils and dna2vec to be called from elsewhere

**Comment by pnpnpn** [comment]
Ah, thank you for noticing this. I had `'.'` permanently added to my `PYTHONPATH`. I made a PR that should fix that: https://github.com/pnpnpn/dna2vec/pull/5. You can now call the training code from both either the project root or `scripts/`. 

I will try to use egg and put it up on pypi.

**Comment by stanleyjs** [comment]
Thanks for fixing this - I will let you know if I run into more problems getting training going, and I'll try to contribute to bugfixes as I go.
